### ISSUE TITLE
Brain dump of questions on supervisors

### ISSUE THREAD

**Issue by m8pple** [POETSII/orchestrator-documentation#8]
Questions occuring based on reading fde82c7196e80f44817c5504f7e89b8489233ea4.
Main docs looked at were:  applications.md and mothership_design.md

- What are the constraints on types used in the SupervisorType::State
  element?

  - Is it any C++ type mentioned in the code section (FILE * is used)?
  - Does it include non-POD types (e.g. std::vector is used in the example)?
  - If pointer types are allowed, is the location of elements in the state
    stable (i.e. can we ratain a pointer; can the supervisor be copied)?

- What is the type of supervisorState? Is it just anything that contains
  the members mentioned in "State".

- Does SupervisorType have Properties?
  - Can you give the supervisor config in the graph instance?
  - Can you initialise supervisor state in the graph instance?
     (This has issues with complex C++ state).

- What is the purpose of  SupervisorInPin attribute? If there is only
  one pin. Or can there be more than one pin?
  - (Note: most attributes have been lower camel case, i.e. "supervisorInPin")

- How does the supervisor send messages to devices?

- The supervisor is guaranteed to only run on one thread, but can it
  run on any thead? (presumably yes)

- Does the description/example in https://github.com/POETSII/orchestrator-documentation/blob/1.0.0-alpha/source/applications.md
  capture all aspects of the XML as seen by the orchestrator?

- Are the definitions of the Supervisor API structs/types defined somewhere.
  - Is there a file which defines SupervisorAPI for any code which is not the orchestrator?
  - What should be included?
  - Is it stable?

- Do the state and handler from the XML always get injected into a class?
  - Are there other methods at the same level in the class?
  - Is there other state (at the same level)?

- Can the supervisor type have extra functions?
  - Is there the equivalent of SharedCode?
  - Is deviceState available as an ambient thing?

- Is the SupervisorAPI callback thing available as an ambient pointer within
  handlers?
  - Everything in the SuperisorAPI is defined as function pointers. Are they really pure C function pointers?
  - 

- How does the information in https://github.com/POETSII/orchestrator-documentation/blob/1.0.0-alpha/source/mothership_design.md#supervisor-api
  link into the documentation in applications.md?

- Super::pos "void Super::post(std::string message): Posts a message to the logserver.".
  - What is a message?
  - Is this just text logging?
  - Does it have to be a single line?

**Comment by mvousden** [comment]
> Questions occuring based on reading [fde82c7](https://github.com/POETSII/orchestrator-documentation/commit/fde82c7196e80f44817c5504f7e89b8489233ea4).
> Main docs looked at were: applications.md and mothership_design.md

Thank you! Bear in mind that `applications.md` is user-facing and is undergoing a rewrite to include context, new macros, and the supervisor API, amongst other things. The Mothership documentation (`mothership_design.md`) is developer-facing.

> * What are the constraints on types used in the SupervisorType::State
>   element?
>   
>   * Is it any C++ type mentioned in the code section (FILE * is used)?
>   * Does it include non-POD types (e.g. std::vector is used in the example)?
>   * If pointer types are allowed, is the location of elements in the state
>     stable (i.e. can we ratain a pointer; can the supervisor be copied)?

POD types and types defined in the `Code` section of XML (possibly through includes) are permitted. Pointers are allowed, and locations are stable until the application is stopped.

> * What is the type of supervisorState? Is it just anything that contains
>   the members mentioned in "State".

It is a structure that contains the fields defined in state. A coming revision will abstract reading/writing state (and reading properties) via preprocessor macros, so no `supervisorState` object will be needed to be used in XML (though it's still there for backwards compatibility). Full definition of this to follow.

> * Does SupervisorType have Properties?
>   
>   * Can you give the supervisor config in the graph instance?
>   * Can you initialise supervisor state in the graph instance?
>     (This has issues with complex C++ state).

Yes - `SupervisorType` has properties. No to both of your other points. If you wish to do this, define the field as a graph-level property.

> * What is the purpose of  SupervisorInPin attribute? If there is only
>   one pin. Or can there be more than one pin?
>   
>   * (Note: most attributes have been lower camel case, i.e. "supervisorInPin")

There can be more than one pin - the `SupervisorInPin` attribute can be used to define a specific pin as the implicit.

> * How does the supervisor send messages to devices?

To be formally defined, but we have a good set of ideas. A good explanation coming soon!

> * The supervisor is guaranteed to only run on one thread, but can it
>   run on any thead? (presumably yes)

The answer to this question is nuanced:

 - Supervisors do not "run", as supervisors are not processes. Supervisors manifest as shared object files that are loaded by the Mothership process that contains them.
 - The Mothership itself is multithreaded, where the loaded Supervisor object exists in 'shared-memory'. The different threads in the Mothership can 'invoke' different Supervisor handlers.
 - Supervisor logic can spawn worker threads, which it must manage itself.

> * Does the description/example in https://github.com/POETSII/orchestrator-documentation/blob/1.0.0-alpha/source/applications.md
>   capture all aspects of the XML as seen by the orchestrator?

No - our intention is to capture 'all aspects' of the XML via a set of examples (see the Orchestrator examples repository), though this is a work in progress.

> * Are the definitions of the Supervisor API structs/types defined somewhere.
>   
>   * Is there a file which defines SupervisorAPI for any code which is not the orchestrator?
>   * What should be included?
>   * Is it stable?

I don't understand this question. The Supervisor API is fundamentally a set of functions that can be called in user code (all of the user-facing functions are defined in the Mothership documentation).

> * Do the state and handler from the XML always get injected into a class?
>   
>   * Are there other methods at the same level in the class?
>   * Is there other state (at the same level)?

I don't understand the intent behind this question. Is this in the context of normal devices or in the context of supervisors? In the former case, no. In the latter case yes, but the class is inaccessible to application writers and is for internal use only.

> * Can the supervisor type have extra functions?
>   
>   * Is there the equivalent of SharedCode?
>   * Is deviceState available as an ambient thing?

Free functions for supervisors can be defined in `Code`. Bear in mind that `deviceState` is not accessible in these functions unless elements of the device state are passed in (directly or by reference) as arguments to the free functions.

> * Is the SupervisorAPI callback thing available as an ambient pointer within
>   handlers?
>   
>   * Everything in the SuperisorAPI is defined as function pointers. Are they really pure C function pointers?

The callback mechanism is a 'backend' consideration to facilitate communication between the 'backend' supervisor code and the Mothership. Handlers call, for example, `Super::post("Some text")`, not any of the backend function pointers.

> * How does the information in https://github.com/POETSII/orchestrator-documentation/blob/1.0.0-alpha/source/mothership_design.md#supervisor-api
>   link into the documentation in applications.md?

It doesn't yet, but it will (I'm still writing it).

> * Super::pos "void Super::post(std::string message): Posts a message to the logserver.".
>   
>   * What is a message?
>   * Is this just text logging?
>   * Does it have to be a single line?

This is just text logging. It doesn't have to be a single line (but it's better). File dumps are better for multiline output, but user preference wins.

**Comment by mvousden** [comment]
The updated documentation (review pending, https://github.com/POETSII/orchestrator-documentation/pull/9), should help answer most of these questions more formally. I'll leave the issue open for a while if you want to add more or respond.
